Anastasiia/header component
safeplace-intl/virtual-community pull request #29
Opened 2023-05-10 12:48 UTC by aerlikh17

- Created new component files in src 
- Added a header to app.tsx file 
- Added font config to tailwindconfig file

2023-05-10 17:01 UTC, e-papanicolas requested changes

2023-05-10 17:01 UTC, e-papanicolas commented on .env.example
Hi @aerlikh17 Can you remove this file from the pull request? We want to leave the example file so that later on when others work on the project, they know what the variable will be.

2023-05-15 11:48 UTC, aerlikh17 commented on .env.example
I am not sure how to remove a single file from a pull request

2023-05-18 20:07 UTC, ssjkhan commented
Please implement the following changes as discussed:

- Topnavbar is the header component
- Remove unnecessary wrappers at this stage
- Export modules from index.ts in each component directory
- Remove LeftNavBar component into it's own directory secondary nav-menu
- Rename files with all lowercases, and dashes instead of spaces

-sk

2023-05-24 19:11 UTC, ssjkhan approved these changes
lgtm

2023-05-24 19:13 UTC, merged